# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a 
# newer version of cucumber-rails. Consider adding your own code to a new file 
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'cucumber/rails'

# Use css instead of xpath for selectors
Capybara.default_selector = :css

# Allow controller exceptions to fail scenarios
ActionController::Base.allow_rescue = false

# VCR Config
VCR.config do |c|
  c.cassette_library_dir = 'features/vcr_cassettes'
  c.stub_with :fakeweb
end

# clean database for each scenario
begin
  DatabaseCleaner.orm = 'mongoid'
  DatabaseCleaner.strategy = :truncation
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

Before do
  module Resque 
    def self.enqueue(klass, *args)
      klass.perform(*args)
    end
  end
end
