development:
  host: localhost
  database: codemav

test:
  host: localhost
  database: codemav_test
  autocreate_indexes: true

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
